### ISSUE TITLE
Essential CUDA functions

### ISSUE THREAD

**Issue by sherjilozair** [sherjilozair/cudnn.cr#3]
While the purpose of this library is to wrap cudnn, some cuda functions (from `cuda_runtime_api.h`) will be essential to use the cudnn interface. We should wrap them as well. For starters, we should wrap

- `cudaMalloc`
- `cudaMemcpy`
- `cudaDeviceSynchronize` 
- `cudaFree`
- `checkCudaErr`

These functions were used in the convolution example provided with cudnn.

**Comment by bararchy** [comment]
Added ++++++
https://github.com/sherjilozair/jet/pull/5/commits/abe630ca631b165b3ad56fd262818c0821202fa4
